### ISSUE TITLE
Add command to download public key from kms-id

### ISSUE THREAD

**Issue by hongkongkiwi** [ericnorris/google-kms-x509#3]
Is it possible to add a command to download the Public Key from an already existing KMS Certificate or Key?

Incase the Public Key is lost after creation it would be great to download just the public key without having to recreate a new root_ca.

**Comment by ericnorris** [comment]
@hongkongkiwi interesting - unless I'm mistaken though, a "public key" on its own is useless, it's the certificate that you would want, right? If you lost the certificate you could re-generate an identical one (since the private key is the same), but there wouldn't be a way to "download" it.

That being said, if you really wanted to download the public key you can do that today with a `gcloud` command: https://cloud.google.com/kms/docs/retrieve-public-key#kms-get-public-key-cli
